package com.flashcard.app.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity representing a single flashcard.
 * Each flashcard contains a question-answer pair and a creation timestamp.
 *
 * @property id Unique identifier for the flashcard, auto-generated by Room.
 * @property question The question text displayed on the front of the flashcard.
 * @property answer The answer text displayed on the back of the flashcard.
 * @property createdAt Timestamp (in milliseconds) when the flashcard was created.
 */
@Entity(tableName = "flashcards")
data class Flashcard(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val question: String,
    val answer: String,
    val createdAt: Long = System.currentTimeMillis()
)
